### PR TITLE
fix jacoco/powermock integration issue #564

### PR DESCRIPTION
**Pull request by astafev**

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks a lot. Have you verified that it works? If you have then this is an awesome fix!! :)

**Comment by astafev** [comment]
Yes, verified on our project on work, but I couldn't reproduce the bug on small project.

**Comment by johanhaleby** [comment]
Ok well at least it's a step in the right direction.

**Comment by astafev** [comment]
now I managed to create simple project with bug :). Here it is: https://github.com/astafev/jacoco-test

**Comment by johanhaleby** [comment]
Cool! So your pull request solves the problems in https://github.com/astafev/jacoco-test?

**Comment by astafev** [comment]
yes)

**Comment by johanhaleby** [comment]
awesome! Thanks a lot.

**Pull request merged**
