### PR TITLE
Update travis-ci configuration

### PR DESCRIPTION
**Pull request by thekingnothing**
Build Mockito 2 is added.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Something seems to be wrong?

**Comment by thekingnothing** [comment]
Mockito 2 module is built only in case profile "mockito2" is used. Otherwise normal build is execute with mockito 1.10 as dependence.
I found out it when I tried execute Mockito 2 build from master and saw compilation errors, but build was marked as Success. 

About jdks, Powermock modifies byte code, so it could be issues which depends on environment.

**Comment by thekingnothing** [comment]
Sorry, I answered from mobile and didn't see that build is failed. I find  reason and now commit fix.

**Comment by thekingnothing** [comment]
As you may see everything is okay, now. By the way, I've removed build on other idk except oraclejdk8

**Comment by thekingnothing** [comment]
I'll clear commit history and open new pull request.

**Comment by johanhaleby** [comment]
Great!

**Pull request closed without merging**
